form_endpoint: ''
pages:
  about: true
  tapahtumat: true
  toiminta: true
sections:
  image_row: true
site:
  url: https://tusmo.fi
social:
  facebook: ''
  instagram: ''
  tiktok: ''
  twitter: ''
  youtube: ''
